readme file is done
GSG-FC03/To-do-Team-5 pull request #6
Opened 2021-07-15 09:20 UTC by ferassmohana

We wrote in the file about these points: 

- Project name
- Project description
- user stories
- Live link [github pages]
- How do I get the project on my local machine?
- team members

Relates #5

2021-07-15 09:24 UTC, Aya74 approved these changes

2021-07-15 09:35 UTC, Yousef-Ahmad1997128 approved these changes

2021-07-15 09:59 UTC, MahmoudJD95 approved these changes

2021-07-15 10:05 UTC, sara219 commented on README.md
> +- Mahmoud Jamal Al-Dabba, gitHub link (https://github.com/MahmoudJD95).
to make the text hyperlink, use it like this `[your name](profile link)`, the result: 

[Aya Mazen Alarayshi](https://github.com/Aya74)

2021-07-15 10:48 UTC, sara219 requested changes
some tips: 

- add the team members at the end of the file 
- add the technology that you use (HTML, CSS, js, local storage)
- always be sure it's comfortable to read!

2021-07-15 10:48 UTC, sara219 commented on README.md
> +The app is built in a way that it is easy for the user to interact with.<br>
add the user stories as points

2021-07-16 09:20 UTC, Yousef-Ahmad1997128 approved these changes

2021-07-16 09:21 UTC, Aya74 approved these changes

2021-07-16 09:29 UTC, sara219 approved these changes

2021-07-16 14:58 UTC, merged